import sys
import peppy
import glob

configfile: "config/config.yaml"
pepfile: config.get("PEP")

SAMPLES = [x.sample_name for x in pep.samples]
SAMPLES = SAMPLES if config.get("RUN_TYPE") == "FULL" else SAMPLES[:4]

SUBSAMPLE_TABLE = pep.subsample_table

subworkflow wgs_wf:
    workdir:
        "../subworkflows/dgrp_wgs/"
    snakefile:
        "../subworkflows/dgrp_wgs/workflow/Snakefile"

subworkflow dgrp_coex_wf:
    workdir:
        "../subworkflows/dgrp_coex/"
    snakefile:
        "../subworkflows/dgrp_coex/workflow/Snakefile"

rule all:
    input:
        dgrp_coex_wf(expand("results/linear_models/{m}/coefs.mat.tsv.gz",m=config.get("LM_MODELS_TO_FIT"))),
        dgrp_coex_wf(expand("results/linear_models/{m}/lm.{r}.tsv.gz",m=config.get("LM_MODELS_TO_FIT"),r=["tidy"])),
        #wgs_wf("results/copies/copies.tsv")


include: "rules/download.smk"
include: "rules/trim.smk"
include: "rules/utils.smk"
include: "rules/vanilla_salmon.smk"
include: "rules/metadata.smk"
include: "rules/repeatmasker.smk"
include: "rules/feature_overlap.smk"
include: "rules/linear_modeling.smk"
