import sys
import peppy
import glob

configfile: "config/config.yaml"
pepfile: config.get("PEP")

SAMPLES = [x.sample_name for x in pep.samples]
SAMPLES = SAMPLES if config.get("RUN_TYPE") == "FULL" else SAMPLES[:4]

SUBSAMPLE_TABLE = pep.subsample_table

subworkflow wgs_wf:
    workdir:
        "../subworkflows/wgs/"
    snakefile:
        "../subworkflows/wgs/workflow/Snakefile"

rule all:
    input:
        expand("results/linear_models/{m}/coefs.mat.tsv.gz",m=config.get("LM_MODELS_TO_FIT")),
        expand("results/linear_models/{m}/lm.{r}.tsv.gz",m=config.get("LM_MODELS_TO_FIT"),r=["tidy","glance","aug"]),
        #wgs_wf("results/copies/copies.tsv")
        #expand("results/linear_models/male_edaseq_qn/chunk_{ch}",ch=[str(x).zfill(4) for x in range(0,config.get("LM_CHUNKS",80))])
        #expand("results/linear_models/{lms}/lm.{r}.tsv.gz",lms=config.get("LM_MODELS_TO_FIT"),r=["tidy","glance"]),
        #expand("results/quantification/vanilla_salmon_tes_transcripts/gene.{x}.sqlite",x=config.get("EXPORT_UNITS")),
        #expand("results/quantification/vanilla_salmon_tes_transcripts/{x}.sqlite",x=config.get("DESEQ2_EXPORT_UNITS")),
        #expand("results/quantification/vanilla_salmon_tes_transcripts/quant/{s}/quant.sf",s=SAMPLES),
        #"results/quantification/vanilla_salmon_tes_transcripts/terminus.done",
        #"results/quantification/vanilla_salmon_tes_transcripts/terminus.tx2group.raw.csv",
        #expand("results/reads/fastp/{s}_r1.trimmed.fq.gz",s="DGRP_Line_100_Female_SAMN09738660")
        #expand("results/reads/dump/{s}/{e}/{r}/",s="DGRP_Line_100_Female_SAMN09738660",e=["SRX4483514"],r=['SRR7619150', 'SRR7619149'])

include: "rules/download.smk"
include: "rules/trim.smk"
include: "rules/utils.smk"
include: "rules/vanilla_salmon.smk"
include: "rules/metadata.smk"
include: "rules/bundle.smk"
include: "rules/repeatmasker.smk"
include: "rules/feature_overlap.smk"
include: "rules/linear_modeling.smk"
