name: tf_kd
pep_version: 2.0.0
sample_table: sample_table.csv
subsample_table: subsample_table.csv

sample_modifiers:
  derive:
      attributes: [path_r1, path_r2]
      sources:
        amarel_novo_r1: /projects/genetics/ellison_lab/data/illumina/RNAseq/novogene_20220425/usftp21.novogene.com/raw_data/{fq_r1}
        amarel_novo_r2: /projects/genetics/ellison_lab/data/illumina/RNAseq/novogene_20220425/usftp21.novogene.com/raw_data/{fq_r2}
