import sys
import peppy
import glob

#configfile: "../../config/config.yaml"
configfile: "config/config.yaml"
pepfile: config.get("PEP")

SAMPLES = [x.sample_name for x in pep.samples]

SUBSAMPLE_TABLE = pep.subsample_table

ruleorder: concat_pe_runs > concat_runs > fasterq_dump

subworkflow wgs_wf:
    workdir:
        "../../dgrp_wgs/"
    snakefile:
        "../../dgrp_wgs/workflow/Snakefile"

subworkflow refs_wf:
    workdir:
        "../../references/"
    snakefile:
        "../../references/workflow/Snakefile"

rule all:
    input:
        expand("results/linear_models/{m}/{qr}/lm.tidy.corrected.tsv.gz",m=config.get("LM_MODELS_TO_FIT"),qr=[0,1,2]),
        expand("results/linear_models/{m}/{qr}/lm.{o}.tsv.gz",m=config.get("LM_MODELS_TO_FIT"),o=["glance","anova","breusch_pagan","rainbow"],qr=[0,1,2]),
        expand("results/linear_models/{m}/{qr}/lm.collected-info.tsv.gz",m=config.get("LM_MODELS_TO_FIT"),qr=[0,1,2]),
        expand("results/linear_models/{m}.collected-info.tsv.gz",m=config.get("LM_MODELS_TO_FIT")),
        expand("results/linear_models/{m}.higher_order_overlap_fisher.rds",m=config.get("LM_MODELS_TO_FIT")),
        "results/linear_models/final-models.collected-info.tsv.gz"

include: "../../../workflow/rules/download.smk"
include: "../../../workflow/rules/trim.smk"
include: "../../../workflow/rules/utils.smk"
include: "../../../workflow/rules/vanilla_salmon.smk"
include: "../../../workflow/rules/metadata.smk"
include: "../../../workflow/rules/linear_modeling.smk"
