# --------------------------- housekeeping -------------------------------------
PEP: config/pep.yaml
RUN_TYPE: test # full, test

# --------------------------- Reference data -----------------------------------
# paths in resources assume you're in the top level ptera directory

# consensus transposon set to use
CONSENSUS_TE_FASTA: resources/Tidalbase_transposon_sequence.fasta.gz # must be gz

# references/resources and version data
FULL_TRANSCRIPT_FASTA: resources/dmel-all-transcript-r6.41.fasta.gz # must be gz
MISCRNA_FASTA: resources/dmel-all-miscRNA-r6.41.fasta.gz
MIRNA_FASTA: resources/dmel-all-miRNA-r6.41.fasta.gz
NCRNA_FASTA: resources/dmel-all-ncRNA-r6.41.fasta.gz
TRNA_FASTA: resources/dmel-all-tRNA-r6.41.fasta.gz
PSEUDOGENE_FASTA: resources/dmel-all-pseudogene-r6.41.fasta.gz
GENOME_FASTA: resources/dmel-all-chromosome-r6.41.fasta.gz
TRANSCRIPTOME_GTF: resources/dmel-all-r6.41.gtf
GAL4_FASTA: resources/S288C_YPL248C_GAL4_coding.fasta.gz
ERCC_FASTA: resources/SRM2374_ambiguities_resolved_NoPolyA_v2.erccs.FASTA.gz
FLYBASE_RELEASE: FB2021_04
GENOME_VERSION: r6.41

#Generate with: https://github.com/mal2017/genome-plus-repeats/tree/e14fed1
COMBINED_TE_GENOME_FA: resources/plus-repeats.fasta.gz
COMBINED_TE_FEATURE_GTF: resources/plus-repeats.gtf

# Salmon indices for standard quantification approach
SALMON_K_PARAM: 31
SALMON_VANILLA_USE_DECOYS: TRUE # note that this won't matter if

# --------------------------- job options --------------------------------------
FASTERQDUMP_MEM: 24000

# Salmon quant (standard quantification approach)
SALMON_VANILLA_BOOTSTRAPS: 20
SALMON_VANILLA_LIBTYPE: SR # standard for dUTP, which the DGRP data is. Confirmed by aligning SAMN09738660 - reads map to (-) strand
SALMON_VANILLA_SEQBIAS: TRUE
SALMON_VANILLA_GCBIAS: TRUE
SALMON_VANILLA_POSBIAS: TRUE
SALMON_VANILLA_USE_AUXTARGETS: TRUE
SALMON_VANILLA_SOFTCLIP: TRUE
SALMON_VANILLA_INCOMPATPRIOR_0: TRUE

# Tximport
# these values will be "counts" for all downstream approaches. This is
# relevant as the input to DESeq2 but also because some normalizations are run
# on these directly. So, that means those normalizations are run on totally raw
# counts if the params below == "no"
SALMON_VANILLA_TXIMPORT_COUNTSFROMABUNDANCE: scaledTPM # no, scaledTPM, lengthScaledTPM
SALMON_VANILLA_TXIMPORT_COUNTSFROMABUNDANCE_TXOUT: dtuScaledTPM # no, scaledTPM, lengthScaledTPM, dtuScaledTPM
SALMON_VANILLA_TXIMPORT_COUNTSFROMABUNDANCE_TERMINUS: scaledTPM # no, scaledTPM, lengthScaledTPM
