# housekeeping
PEP: config/pep.yaml
RUN_TYPE: test # full, test

# Refs
CONSENSUS_TE_FASTA: resources/Tidalbase_transposon_sequence.fasta.gz # must be gz
FULL_TRANSCRIPT_FASTA: resources/dmel-all-transcript-r6.41.fasta.gz # must be gz
GENOME_FASTA: resources/dmel-all-chromosome-r6.41.fasta.gz
TRANSCRIPTOME_GTF: resources/dmel-all-r6.41.gtf
FLYBASE_RELEASE: FB2021_04
GENOME_VERSION: r6.41

# Salmon indices for standard quantification approach
SALMON_K_PARAM: 31

# Salmon quant (standard quantification approach)
SALMON_VANILLA_BOOTSTRAPS: 20
SALMON_VANILLA_LIBTYPE: SR # standard for dUTP, which the DGRP data is. Confirmed by aligning SAMN09738660 - reads map to (-) strand
SALMON_VANILLA_SEQBIAS: TRUE
SALMON_VANILLA_GCBIAS: TRUE
SALMON_VANILLA_POSBIAS: TRUE
SALMON_VANILLA_USE_AUXTARGETS: FALSE
SALMON_VANILLA_USE_DECOYS: TRUE
SALMON_VANILLA_SOFTCLIP: TRUE
SALMON_VANILLA_TXIMPORT_COUNTSFROMABUNDANCE: scaledTPM # no, scaledTPM, lengthScaledTPM
SALMON_VANILLA_TXIMPORT_COUNTSFROMABUNDANCE_TXOUT: dtuScaledTPM # no, scaledTPM, lengthScaledTPM, dtuScaledTPM
SALMON_VANILLA_TXIMPORT_COUNTSFROMABUNDANCE_TERMINUS: scaledTPM # no, scaledTPM, lengthScaledTPM

# DESeq2 on salmon
DESEQ2_LRT_FORMULA: ~ Strain + sex # not used right now
DESEQ2_LRT_REDUCED_FORMULA: ~ 1 # not used right now
DESEQ2_RLOG_FITTYPE: local
DESEQ2_VST_FITTYPE: local
