# housekeeping
PEP: config/pep.yaml
RUN_TYPE: test # full, test

# Refs
CONSENSUS_TE_FASTA: resources/Tidalbase_transposon_sequence.fasta.gz # must be gz
FULL_TRANSCRIPT_FASTA: resources/dmel-all-transcript-r6.41.fasta.gz # must be gz
GENOME_FASTA: resources/dmel-all-chromosome-r6.41.fasta.gz
TRANSCRIPTOME_GTF: resources/dmel-all-r6.41.gtf
FLYBASE_RELEASE: FB2021_04
GENOME_VERSION: r6.41

# Salmon indices for standard quantification approach
SALMON_K_PARAM: 31

# Salmon quant (standard quantification approach)
SALMON_VANILLA_BOOTSTRAPS: 20
SALMON_VANILLA_LIBTYPE: SR # standard for dUTP, which the DGRP data is. Confirmed by aligning SAMN09738660 - reads map to (-) strand
SALMON_VANILLA_SEQBIAS: TRUE
SALMON_VANILLA_GCBIAS: TRUE
SALMON_VANILLA_POSBIAS: TRUE
SALMON_VANILLA_USE_AUXTARGETS: FALSE
SALMON_VANILLA_USE_DECOYS: TRUE
SALMON_VANILLA_SOFTCLIP: TRUE
SALMON_VANILLA_TXIMPORT_COUNTSFROMABUNDANCE: scaledTPM # no, scaledTPM, lengthScaledTPM
SALMON_VANILLA_TXIMPORT_COUNTSFROMABUNDANCE_TXOUT: dtuScaledTPM # no, scaledTPM, lengthScaledTPM, dtuScaledTPM
SALMON_VANILLA_TXIMPORT_COUNTSFROMABUNDANCE_TERMINUS: scaledTPM # no, scaledTPM, lengthScaledTPM

# DESeq2 on salmon
DESEQ2_LRT_FORMULA: ~ Strain + sex # not used right now
DESEQ2_LRT_REDUCED_FORMULA: ~ 1 # not used right now
DESEQ2_EXPORT_UNITS: ["vst","normcts","fpkm"] # ["vst","raw","normcts","fpkm","abundance","cpm"]
DESEQ2_RLOG_FITTYPE: local
DESEQ2_VST_FITTYPE: local

# basic linear model options
# Provid
# Current other variables: wolbachia, sex, Strain (though this wouldn't make sense), age (all the same in these data)
LM_MODELS_TO_FIT:
  y_~_x_+_wolbachia_by_sex_salmon_vst: # the name for the lm fitting run. Will be a directory in the linear_modeling output dir
    LM_FIT_FOR_PIPELINE: vanilla_salmon_tes_transcripts # currently the only option
    LM_FIT_FOR_UNITS: vst
    LM_FORMULA: y ~ x + wolbachia
    LM_SPLIT_BY: ["sex"]
    LM_GENE_FILTER: "sum(x <=0) != 800"
    LM_TE_FILTER: "sum(y <=0) != 800"
    LM_VARIABLE_TRANSFORM: NA # purr style lambda to transform any of the nonbinary variables
