# --------------------------- housekeeping -------------------------------------
PEP: config/pep.yaml


# --------------------------- job options --------------------------------------
FASTERQDUMP_MEM: 24000
