import sys
import peppy
import glob

configfile: "../../config/config.yaml"
#configfile: "config/config.yaml"
pepfile: config.get("PEP")

SAMPLES = [x.sample_name for x in pep.samples]

subworkflow refs_wf:
    workdir:
        "../../references/"
    snakefile:
        "../../references/workflow/Snakefile"

rule all:
    input:
        #expand("results/downstream/single_sample_dimred/{s}.usa.filt.dimred.sce.rds",s=SAMPLES),
        expand("results/downstream/integrated_by_tissue_and_sex_dge/{t_s}.dge.tsv.gz",t_s=[["head_female","head_male","ovary_female","testis_male"][i] for i in [0]])

include: "rules/alevin-fry.smk"
include: "rules/initial_scrna_steps.smk"
